version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /services/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
    groups:
      go-modules:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
